### ISSUE TITLE
为什么会报权限不够

### ISSUE THREAD

**Issue by powerLxc** [glaciall/jtt1078-video-server#4]
java.lang.RuntimeException: java.io.IOException: Cannot run program "/monchickey/mkfifo": error=13, 权限不够
	at cn.org.hentai.jtt1078.video.PublisherManager.mkfifo(PublisherManager.java:230)
	at cn.org.hentai.jtt1078.video.PublisherManager.access$100(PublisherManager.java:20)
	at cn.org.hentai.jtt1078.video.PublisherManager$Publisher.open(PublisherManager.java:143)
	at cn.org.hentai.jtt1078.video.PublisherManager.request(PublisherManager.java:66)
	at cn.org.hentai.jtt1078.server.Jtt1078Handler.channelRead0(Jtt1078Handler.java:47)
	at cn.org.hentai.jtt1078.server.Jtt1078Handler.channelRead0(Jtt1078Handler.java:19)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/monchickey/mkfifo": error=13, 权限不够
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at cn.org.hentai.jtt1078.video.PublisherManager.mkfifo(PublisherManager.java:224)
	... 26 more
Caused by: java.io.IOException: error=13, 权限不够
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more

**Comment by powerLxc** [comment]
mkfifo这是个文件夹还是什么文件,我创建了这个文件夹,并且把权限设置成777了

**Comment by glaciall** [comment]
`mkfifo`是一个命令行，是`linux`下所特有的一个，你先通过`which mkfifo`来确定一下它的路径，一般情况下都是默认路径，你不需要改的，我只是提供了一个修改的可能性，如果你的位置不一样才需要改它，你恢复成原样的就好了，那个`fifo-pool.path`才是一个目录。。。。这里保存fifo命令管道文件的。。。。

**Comment by glaciall** [comment]
很可耻的是我忘了给配置文件写注释了，真是不好意思，今天晚上我改一改。。。。

**Comment by powerLxc** [comment]
谢谢解答
